package com.tzion.jetpackmovies.network.model

internal object Constants {
    const val SEARCH = "Search"
    const val TITLE = "Title"
    const val YEAR = "Year"
    const val IMDBID = "imdbID"
    const val TYPE = "Type"
    const val POSTER = "Poster"
    const val RATED = "Rated"
    const val RELEASED = "Released"
    const val RUNTIME = "Runtime"
    const val GENRE = "Genre"
    const val DIRECTOR = "Director"
    const val WRITER = "Writer"
    const val ACTORS = "Actors"
    const val PLOT = "Plot"
    const val LANGUAGE = "Language"
    const val COUNTRY = "Country"
    const val AWARDS = "Awards"
    const val RATINGS = "Ratings"
    const val METASCORE = "Metascore"
    const val IMDB_RATING = "imdbRating"
    const val IMDB_VOTES = "imdbVotes"
    const val IMDB_ID = "imdbID"
    const val DVD = "DVD"
    const val BOX_OFFICE = "BoxOffice"
    const val PRODUCTION = "Production"
    const val WEBSITE = "Website"
    const val RESPONSE = "Response"
    const val SOURCE = "Source"
    const val VALUE = "Value"
}
